### ISSUE TITLE
tcp client的例子跑一下就死了

### ISSUE THREAD

**Issue by linany** [fwhezfwhez/tcpx#50]
```
[0 0 0 31 0 0 0 6 0 0 0 2 0 0 0 17 123 125 34 109 121 32 110 97 109 101 32 105 115 32 116 99 112 120 34]
收到服务端消息块: {
    "message_id": 6,
    "header": {},
    "body": "my name is tcpx"
  }
服务端消息: my name is tcpx
panic: 2021-03-05 14:49:01 | /root/go/src/github.com/fwhezfwhez/tcpx/examples/sayHello/client/main.go:29 | EOF


goroutine 7 [running]:
main.main.func1(0x813a20, 0xc00000e080)
        /root/go/src/github.com/fwhezfwhez/tcpx/examples/sayHello/client/main.go:29 +0x42b
created by main.main
        /root/go/src/github.com/fwhezfwhez/tcpx/examples/sayHello/client/main.go:22 +0xbe
exit status 2
```
是bug还是我用的不对呢，我按照readme来的。

**Comment by fwhezfwhez** [comment]
你好，可以将服务端代码里的心跳机制注释掉，就好了

```go
srv.HeartBeatMode(true, 5*time.Second)

srv.RewriteHeartBeatHandler(20, func(c *tcpx.Context) {
fmt.Println("rewrite heartbeat and receive from client")
})
```

等学会了如何使用心跳的模块后，再解回来

**Comment by fwhezfwhez** [comment]
如果未解决，请重新打开
